### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by rDarge** [K-RT-Dev/VGT#3]
This is really cool! I'd like to contribute, but there's no license established in the repo so far. Is collaboration something you're open to, or are you not sure where you'd like to go with the project?

**Comment by rDarge** [comment]
Ah - I see the MIT license is indicated in the package.json. Is that intentional?

**Comment by K-RT-Dev** [comment]
I have added the MIT license. Feel free to use this repository for whatever you want
