### ISSUE TITLE
How do I cleanly delete it?

### ISSUE THREAD

**Issue by audegsper** [K-RT-Dev/VGT#4]
It does not support delete programs. Where were the files saved during installation?

**Comment by K-RT-Dev** [comment]
When installing the program, a folder called 'VGT' is generated in AppData, you must delete that directory. (This is the directory created by [ElectronJS](https://www.electronjs.org/docs/latest/api/app#appgetpathname))

On the other hand, the OCR models are downloaded to the `.cache\huggingface` folder located in the user's main directory. (This is the location where the models downloaded from [Huggingface ](https://huggingface.co/docs/datasets/cache) are saved by default) 

By deleting those two elements and the folder where the VGT.exe is located, you remove everything
